require('basic')
require('plugin')
require('keybindings')
require('plugin-config/nvim-tree')
require('plugin-config/bufferline')
require('plugin-config/tokyonight')
require('plugin-config/lualine')
require('plugin-config/nvim-treesitter')
-- require('plugin-config/scrollbar')
require('plugin-config/hlslens')
require('plugin-config/comment')
-- require('plugin-config/minimap')
require('plugin-config/satellite')
-- require('plugin-config/gruvbox')
require('plugin-config/markdown-preview')

require('lsp/setup')
require('lsp/nvim-cmp')

